### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Benees** [shuffle-project/melvin#79]
- [ ] Du hast im HTML-Tag die richtige Sprache angegeben, allerdings können die Transkript-Texte und der Titel sich zu dieser Sprache unterscheiden, wie hier in diesem Beispiel. Da solltest du das richtige Language Tag noch setzen
Bene: versteh ich nicht

- [x]  Der Inner-Slider um die Videogröße anzupassen ist nur 11px breit mit jeweils 1px links und recht margin. Insgesamt, sollte er mindestens 24px breit sein. Also wenn du den Margin behalten willst: width: 1.375rem; margin-inline: 1px; box-sizing: border-box; padding-inline: 0.1875rem

- [x] Der Titel des Projektes oben links ist in einem H2-Element. Sollte aber ein h1 sein

- [x]  Wenn ich über das Gebärdensprache-Video hover, dann taucht der Titel und links davor das Icon auf. Die sind allerdings vertical nicht in der Mitte aligned. Ein kleiner Abstand von 0.25rem zwischen den beiden würde sicher auch gut aussehen

- [x] scheint wohl mein Fehler zu sein. Der Vertical Slider um die Video-Größe anzupassen hat das richtige Aria-Label in der richtigen Sprache, allerdings wird unter Chrome und Mac mir das Label nicht vorgelesen sondern nur "vertikal Teiliungsfunktion"

- [x] Das Melvin-Logo oben rechts hat einen Tabindex=0, man kann also hintabben, allerdings hat es Stand jetzt keine Funktion. Außerdem hat das Logo nur den Alt-Text="Logo". Vielleicht lieber "Melvin-Logo", sonst kann es ja alles sein

- [x]  Kleinigkeit: Wenn man bei YouTube den Volume-Slider auf 0% zieht, dann passt sich das Icon links davon an und wird durchgestrichen. Keine Ahnung, ob wir das auch wollen. Ist dann halt mehr stimmig

- [x] Wenn man bei dem vertical Slider, um die Videogröße anzupassen, hintabt, wird natürlich die Outline angezeigt. Diese wird aber zum Großteil von den Videos überdeckt. Hier wäre es wahrscheinlich sinnvoll ein css "outline-offset: -1px" zu setzen, vielleicht auch -2px. In Kombination mit outline-width von 2px

- [ ] Die zusätzlichen Videos kann man antabben, allerdings nicht anklicken. Man muss dann nochmal tabben, um zu den "Switch-Button" zu kommen. Hier ist die Frage, ob man das nicht so machen kann, dass man beim tabben direkt auf den richtigen Button springt. Hier sollte dann auch die richtige Outline sein. Ich empfehle "outline: 2px solid var(--color-white)" und "outline-offset: 2px"

Ergänzung zu 10) Scheint nur bei Firefox so zu sein ...
... und das kann man, glaub ich, nicht ausstellen. Dann sollte man dem Video aber auch eine 2px breite outline geben, die ein offset von -2px hat

- [x] Wenn ich beispielsweise durch das Sprach-Untermenü gehe, dann haben die Buttons beim tabben auch nur einen leichten Hintergrund aber keine Outline. Man sieht den Fokus fast gar nicht.

- [ ] Die Sprachmenü-Optionen haben zwar role="menuitem" aber keine Verbindung zu den restlichen Optionen. Das div, welches die Optionen enthält sollte eine role="group" haben und aria-labelledby= (... hier die Überschrift der Menu-Section, also bspw. Untertitel)

...also damit man weiß, dass die Option "Aus" zu "Untertitel", als Beispiel

- [ ]  Die Einstellung Captions Position scheint zumindest bei mir unter Chrome und Firefox nicht richtig zu funktionieren. Bei "Above the video", wird es trotzdem unten angezeigt, allerdings kann man die Untertitel sehen. Wählt man nämlich "Below the video" aus, verschwinden sie ganz 😅

- [ ] Ich denke für Menschen mit einer visuellen Beeinträchtigung, die gerne Sachen vergrößern, wäre es ganz gut, wenn wir bei "Caption Fontsize" eine Option mit 200% anbieten könnten 🙂

- [ ]  Wenn man über den Browser zoomt, zerstört das, glaub ich, die Scroll Automatically funktion, also man kann sie noch aktivieren, aber es scrollt nicht mehr richtig mit. Zumindest unter Firefox war das so. Muss man wahrscheinlich ausgiebiger testen
... das Zoomen wird auch ein Problem für die weiteren Videos, da die deutlich mehr dadurch von dem Player Menü und header überdeckt werden

- [x]  Im Settings Menü macht der Help Button bei mir nichts 
 Bene: ja gut, was soll er auch machen ? :D

**Comment by KorbinianKuhn** [comment]
Von mir aus könnte man den Hintergrund von dem Video-Split-Element komplett wegmachen und nur bei Hover anzeigen

**Comment by niklasegger** [comment]
Punkt 1 von Kobi find ich eine gute Idee und Punkt 2 habe ich ähnlich auch schon oben irgendwo hingeschrieben. Kobis Version ist nochmal detailierter
